# Generated by Django 6.0.3 on 2026-03-20 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Nova Conversa",
                        help_text="Título da conversa, exibido na sidebar",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Arquivo PDF ou DOCX enviado", upload_to="documents/"
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="Nome original do arquivo (ex: relatorio.pdf)",
                        max_length=255,
                    ),
                ),
                (
                    "extracted_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Texto extraído do documento (gerado automaticamente)",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="Resumo gerado pelo LLM", null=True
                    ),
                ),
                (
                    "is_indexed",
                    models.BooleanField(
                        default=False,
                        help_text="Se o documento já foi indexado no ChromaDB (Milestone 3)",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="chat.conversation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "Usuário"),
                            ("assistant", "Assistente"),
                            ("system", "Sistema"),
                        ],
                        help_text="Quem enviou: user, assistant, ou system",
                        max_length=10,
                    ),
                ),
                ("content", models.TextField(help_text="O conteúdo da mensagem")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
